### ISSUE TITLE
Result visualization

### ISSUE THREAD

**Issue by RuipingL** [jhcho99/CoFormer#1]
Dear authors,

Thank you for your impressive work. I would like to know if you can provide the function to visualize the Coformer outputs.

Best

**Comment by BudBudding** [comment]
@RuipingL Hello, have you resolved this issue? Would it be convenient to share it? I hope to receive your reply! Thank you.

**Comment by RuipingL** [comment]
> @RuipingL Hello, have you resolved this issue? Would it be convenient to share it? I hope to receive your reply! Thank you.

use the inference.py file. My project [OpenSU](https://github.com/RuipingL/OpenSU) is based on it. You can check it out.
